[workspace]
members = [
  "castaway",
  "daemon",
  "engine",
  "once",
  "pounce",
  "queuey-queue",
  "utils"
]

[workspace.dependencies]
anyhow = "1.0.66"
axum = "0.6.1"
clap = { version = "3.2.23", features = ["derive"] }
dotenvy = "0.15.6"
env_logger = "0.10.0"
log = "0.4.17"
tokio = { version = "1.22.0", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["io"] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }
