[package]
name = "wait-for-it"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
wasi-common = "3.0.1"
wasmtime = "3.0.1"
wasmtime-wasi = "3.0.1"
