[package]
name = "queuey-queue"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause-Patent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
axum = "0.6.1"
chrono = "0.4.23"
dotenvy = "0.15.6"
env_logger = "0.10.0"
if-addrs = "0.7.0"
log = "0.4.17"
mdns-sd = "0.5.9"
once_cell = "1.16.0"
tokio = { version = "1.22.0", features = ["full"] }
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
