name: "Main branch checks"
on:
  push:
    branches: [ "main" ]
    paths:
      - "**/src/**"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/main.yaml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: get cargo-nextest on path
        run: |
          curl -sL https://get.nexte.st/latest/linux -o nextest.tgz
          tar xfz nextest.tgz
          mv cargo-nextest /home/runner/.cargo/bin

      - name: run the tests
        run: cargo nextest run

      - name: get clippy's blessing
        run: cargo clippy --all-targets -- -D warnings

      - name: finally, get picky about formatting
        run: cargo fmt --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          log-level: warn
          command: check
          command-arguments: "licenses"
